export const NOTE_NAMES = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B'];
export const STRING_PC = [4,9,2,7,11,4];

export const QUALITIES = [
  { key:"maj7", label:"maj7", suffix:"maj7", intervals:[0, 4, 7, 11] },
  { key:"m7", label:"m7", suffix:"m7", intervals:[0, 3, 7, 10] },
  { key:"7", label:"7", suffix:"7", intervals:[0, 4, 7, 10] },
  { key:"m7b5", label:"m7♭5", suffix:"m7♭5", intervals:[0, 3, 6, 10] },
  { key:"dim7", label:"dim7", suffix:"dim7", intervals:[0, 3, 6, 9] },
  { key:"maj9", label:"maj9", suffix:"maj9", intervals:[0, 4, 7, 11, 14] },
  { key:"m9", label:"m9", suffix:"m9", intervals:[0, 3, 7, 10, 14] },
  { key:"9", label:"9", suffix:"9", intervals:[0, 4, 7, 10, 14] },
  { key:"13", label:"13", suffix:"13", intervals:[0, 4, 7, 10, 14, 21] },
  { key:"6/9", label:"6/9", suffix:"6/9", intervals:[0, 4, 7, 9, 14] },
  { key:"m11", label:"m11", suffix:"m11", intervals:[0, 3, 7, 10, 14, 17] },
  { key:"7sus4", label:"7sus4", suffix:"7sus4", intervals:[0, 5, 7, 10] },
  { key:"7alt", label:"7alt", suffix:"7alt", intervals:[0, 4, 10, 13, 15, 20] },
];

export const FAMILIES = ['all','open','caged','shell','drop2','drop3','rootless','compact'];
export const USAGES = ['all','beginner','pop','jazz-comping','bossa','solo-guitar','funk','blues'];

// frets: 6弦 -> 1弦。null はミュート。rootless は root を含まない実用ジャズフォーム。
// Phase 1 seed: maj7 / m7 / 7 / m7b5 / dim7 を厚めにし、テンション系をスターターとして追加。
export const CHORD_LIBRARY = [
  {quality:"maj7", name:"Open Cmaj7", frets:[null, 3, 2, 0, 0, 0], family:"open", usage:["beginner", "pop"], difficulty:1, popularity:86, jazz:78, tags:["open", "beginner"]},
  {quality:"maj7", name:"CAGED A-shape maj7", frets:[null, 3, 5, 4, 5, 3], family:"caged", usage:["jazz-comping", "bossa", "pop"], difficulty:2, popularity:80, jazz:84, tags:["movable", "caged"]},
  {quality:"maj7", name:"CAGED E-shape maj7", frets:[8, 10, 9, 9, 8, 8], family:"caged", usage:["jazz-comping", "solo-guitar"], difficulty:4, popularity:54, jazz:82, tags:["movable", "barre"]},
  {quality:"maj7", name:"Shell 5th string root", frets:[null, 3, 2, 4, null, null], family:"shell", usage:["jazz-comping", "bossa"], difficulty:1, popularity:78, jazz:91, tags:["shell", "guide-tones"]},
  {quality:"maj7", name:"Shell 6th string root", frets:[8, null, 9, 9, null, null], family:"shell", usage:["jazz-comping"], difficulty:2, popularity:70, jazz:90, tags:["shell", "guide-tones"]},
  {quality:"maj7", name:"Shell compact middle", frets:[null, null, 10, 9, 8, null], family:"shell", usage:["jazz-comping", "funk"], difficulty:2, popularity:62, jazz:88, tags:["shell", "compact"]},
  {quality:"maj7", name:"Drop2 6th string root", frets:[8, null, 9, 9, 8, null], family:"drop2", usage:["jazz-comping"], difficulty:3, popularity:68, jazz:94, tags:["drop2", "compact"]},
  {quality:"maj7", name:"Drop2 5th string root", frets:[null, 3, 5, 4, 5, null], family:"drop2", usage:["jazz-comping", "bossa"], difficulty:3, popularity:72, jazz:93, tags:["drop2"]},
  {quality:"maj7", name:"Drop2 top-set", frets:[null, null, 10, 9, 8, 7], family:"drop2", usage:["jazz-comping", "solo-guitar"], difficulty:4, popularity:50, jazz:91, tags:["drop2", "top-set"]},
  {quality:"maj7", name:"Drop3 6th string root", frets:[8, 7, 9, 9, null, null], family:"drop3", usage:["solo-guitar", "jazz-comping"], difficulty:4, popularity:48, jazz:88, tags:["drop3"]},
  {quality:"maj7", name:"Rootless 3-7-9-5", frets:[null, null, 2, 4, 3, 3], family:"rootless", usage:["jazz-comping", "bossa"], difficulty:3, popularity:63, jazz:97, rootless:true, tags:["rootless", "9th"]},
  {quality:"maj7", name:"Rootless 7-3-5-9", frets:[null, null, 5, 5, 5, 7], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:45, jazz:95, rootless:true, tags:["rootless", "upper-structure"]},
  {quality:"m7", name:"Open Cm7 color", frets:[null, 3, 1, 3, 1, null], family:"open", usage:["pop", "bossa"], difficulty:2, popularity:55, jazz:76, tags:["open-ish"]},
  {quality:"m7", name:"CAGED Am-shape m7", frets:[null, 3, 5, 3, 4, 3], family:"caged", usage:["jazz-comping", "bossa", "pop"], difficulty:2, popularity:84, jazz:86, tags:["movable", "caged"]},
  {quality:"m7", name:"CAGED Em-shape m7", frets:[8, 10, 8, 8, 8, 8], family:"caged", usage:["jazz-comping"], difficulty:3, popularity:76, jazz:84, tags:["barre"]},
  {quality:"m7", name:"Shell 5th string root", frets:[null, 3, 1, 3, null, null], family:"shell", usage:["jazz-comping", "bossa"], difficulty:1, popularity:82, jazz:92, tags:["shell", "guide-tones"]},
  {quality:"m7", name:"Shell 6th string root", frets:[8, null, 8, 8, null, null], family:"shell", usage:["jazz-comping"], difficulty:2, popularity:73, jazz:91, tags:["shell", "guide-tones"]},
  {quality:"m7", name:"Shell compact middle", frets:[null, null, 10, 8, 8, null], family:"shell", usage:["jazz-comping", "funk"], difficulty:2, popularity:60, jazz:88, tags:["shell", "compact"]},
  {quality:"m7", name:"Drop2 6th string root", frets:[8, null, 8, 8, 8, null], family:"drop2", usage:["jazz-comping"], difficulty:2, popularity:74, jazz:94, tags:["drop2"]},
  {quality:"m7", name:"Drop2 5th string root", frets:[null, 3, 5, 3, 4, null], family:"drop2", usage:["jazz-comping", "bossa"], difficulty:3, popularity:71, jazz:92, tags:["drop2"]},
  {quality:"m7", name:"Drop2 top-set", frets:[null, null, 10, 8, 8, 6], family:"drop2", usage:["jazz-comping", "solo-guitar"], difficulty:4, popularity:46, jazz:91, tags:["drop2", "top-set"]},
  {quality:"m7", name:"Drop3 6th string root", frets:[8, 6, 8, 8, null, null], family:"drop3", usage:["solo-guitar", "jazz-comping"], difficulty:4, popularity:44, jazz:88, tags:["drop3"]},
  {quality:"m7", name:"Rootless b3-b7-9-5", frets:[null, null, 1, 3, 3, 3], family:"rootless", usage:["jazz-comping", "bossa"], difficulty:3, popularity:64, jazz:97, rootless:true, tags:["rootless", "9th"]},
  {quality:"m7", name:"Rootless b7-b3-5-9", frets:[null, null, 3, 3, 4, 6], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:43, jazz:94, rootless:true, tags:["rootless", "upper-structure"]},
  {quality:"7", name:"Open C7", frets:[null, 3, 2, 3, 1, 0], family:"open", usage:["beginner", "pop", "blues"], difficulty:1, popularity:88, jazz:76, tags:["open", "beginner"]},
  {quality:"7", name:"CAGED A7-shape", frets:[null, 3, 5, 3, 5, 3], family:"caged", usage:["jazz-comping", "bossa", "funk"], difficulty:2, popularity:86, jazz:84, tags:["movable", "caged"]},
  {quality:"7", name:"CAGED E7-shape", frets:[8, 10, 8, 9, 8, 8], family:"caged", usage:["jazz-comping", "blues"], difficulty:3, popularity:80, jazz:83, tags:["barre"]},
  {quality:"7", name:"Shell 5th string root", frets:[null, 3, 2, 3, null, null], family:"shell", usage:["jazz-comping", "bossa"], difficulty:1, popularity:84, jazz:93, tags:["shell", "guide-tones"]},
  {quality:"7", name:"Shell 6th string root", frets:[8, null, 8, 9, null, null], family:"shell", usage:["jazz-comping"], difficulty:2, popularity:75, jazz:92, tags:["shell", "guide-tones"]},
  {quality:"7", name:"Shell compact middle", frets:[null, null, 10, 9, 8, null], family:"shell", usage:["jazz-comping", "funk"], difficulty:2, popularity:63, jazz:90, tags:["shell", "compact"]},
  {quality:"7", name:"Drop2 6th string root", frets:[8, null, 8, 9, 8, null], family:"drop2", usage:["jazz-comping"], difficulty:3, popularity:74, jazz:95, tags:["drop2"]},
  {quality:"7", name:"Drop2 5th string root", frets:[null, 3, 5, 3, 5, null], family:"drop2", usage:["jazz-comping", "bossa"], difficulty:3, popularity:73, jazz:93, tags:["drop2"]},
  {quality:"7", name:"Drop2 top-set", frets:[null, null, 10, 9, 8, 6], family:"drop2", usage:["jazz-comping", "solo-guitar"], difficulty:4, popularity:47, jazz:91, tags:["drop2", "top-set"]},
  {quality:"7", name:"Drop3 6th string root", frets:[8, 8, 8, 9, null, null], family:"drop3", usage:["solo-guitar", "jazz-comping"], difficulty:4, popularity:46, jazz:89, tags:["drop3"]},
  {quality:"7", name:"Rootless 3-b7-9-13", frets:[null, null, 2, 3, 3, 5], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:68, jazz:98, rootless:true, tags:["rootless", "9th", "13th"]},
  {quality:"7", name:"Rootless b7-3-13-9", frets:[null, null, 3, 4, 5, 3], family:"rootless", usage:["jazz-comping", "funk"], difficulty:4, popularity:58, jazz:96, rootless:true, tags:["rootless", "13th"]},
  {quality:"7", name:"Funk 9 compact", frets:[null, 3, 2, 3, 3, null], family:"compact", usage:["funk", "jazz-comping"], difficulty:2, popularity:78, jazz:91, tags:["9th", "compact"]},
  {quality:"m7b5", name:"Compact m7b5", frets:[null, 3, 4, 3, 4, null], family:"compact", usage:["jazz-comping"], difficulty:3, popularity:66, jazz:95, tags:["minor-ii-v", "compact"]},
  {quality:"m7b5", name:"Shell m7b5", frets:[null, 3, 1, 3, 2, null], family:"shell", usage:["jazz-comping"], difficulty:3, popularity:60, jazz:93, tags:["shell", "minor-ii-v"]},
  {quality:"m7b5", name:"6th string m7b5", frets:[8, null, 8, 8, 7, null], family:"drop2", usage:["jazz-comping"], difficulty:3, popularity:52, jazz:92, tags:["drop2", "minor-ii-v"]},
  {quality:"m7b5", name:"Top-set m7b5", frets:[null, null, 10, 11, 11, 11], family:"drop2", usage:["jazz-comping", "solo-guitar"], difficulty:4, popularity:38, jazz:90, tags:["top-set"]},
  {quality:"m7b5", name:"Rootless m7b5 color", frets:[null, null, 1, 3, 2, 2], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:46, jazz:94, rootless:true, tags:["rootless", "minor-ii-v"]},
  {quality:"m7b5", name:"Rootless b5-b7-b3-11", frets:[null, null, 4, 3, 4, 6], family:"rootless", usage:["jazz-comping"], difficulty:5, popularity:34, jazz:93, rootless:true, tags:["rootless", "color"]},
  {quality:"m7b5", name:"Drop3 m7b5", frets:[8, 6, 8, 8, 7, null], family:"drop3", usage:["solo-guitar", "jazz-comping"], difficulty:5, popularity:32, jazz:90, tags:["drop3"]},
  {quality:"m7b5", name:"Easy inner m7b5", frets:[null, null, 4, 3, 4, null], family:"compact", usage:["jazz-comping"], difficulty:2, popularity:50, jazz:88, tags:["compact"]},
  {quality:"dim7", name:"Classic dim7", frets:[null, 3, 4, 2, 4, 2], family:"compact", usage:["jazz-comping", "solo-guitar"], difficulty:3, popularity:64, jazz:91, tags:["symmetrical"]},
  {quality:"dim7", name:"High compact dim7", frets:[null, null, 4, 5, 4, 5], family:"compact", usage:["jazz-comping"], difficulty:3, popularity:54, jazz:89, tags:["symmetrical", "compact"]},
  {quality:"dim7", name:"Low dim7 grip", frets:[null, 3, 1, 2, 1, null], family:"compact", usage:["jazz-comping"], difficulty:3, popularity:50, jazz:88, tags:["symmetrical"]},
  {quality:"dim7", name:"Drop2 dim7", frets:[8, null, 7, 8, 7, null], family:"drop2", usage:["jazz-comping"], difficulty:4, popularity:42, jazz:89, tags:["drop2", "symmetrical"]},
  {quality:"dim7", name:"Rootless passing dim", frets:[null, null, 1, 2, 1, 2], family:"rootless", usage:["jazz-comping"], difficulty:3, popularity:48, jazz:90, rootless:true, tags:["rootless", "passing"]},
  {quality:"dim7", name:"Solo guitar dim7", frets:[8, 9, 10, 8, null, null], family:"drop3", usage:["solo-guitar"], difficulty:5, popularity:30, jazz:86, tags:["drop3", "symmetrical"]},
  {quality:"maj9", name:"Rootless maj9", frets:[null, null, 2, 4, 3, 3], family:"rootless", usage:["jazz-comping", "bossa"], difficulty:3, popularity:70, jazz:98, rootless:true, tags:["rootless", "9th"]},
  {quality:"maj9", name:"Maj9 5th string root", frets:[null, 3, 2, 4, 3, null], family:"shell", usage:["jazz-comping", "bossa"], difficulty:2, popularity:68, jazz:95, tags:["9th", "shell"]},
  {quality:"maj9", name:"Maj9 spread", frets:[8, null, 9, 9, 8, 10], family:"drop2", usage:["solo-guitar", "bossa"], difficulty:5, popularity:36, jazz:92, tags:["spread", "9th"]},
  {quality:"maj9", name:"Maj9 compact", frets:[null, 3, 5, 4, 3, null], family:"compact", usage:["bossa", "jazz-comping"], difficulty:3, popularity:58, jazz:94, tags:["compact", "9th"]},
  {quality:"maj9", name:"Rootless maj9 high", frets:[null, null, 5, 5, 7, 7], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:42, jazz:95, rootless:true, tags:["rootless", "top-set"]},
  {quality:"m9", name:"Rootless m9", frets:[null, null, 1, 3, 3, 3], family:"rootless", usage:["jazz-comping", "bossa"], difficulty:3, popularity:68, jazz:97, rootless:true, tags:["rootless", "9th"]},
  {quality:"m9", name:"m9 shell", frets:[null, 3, 1, 3, 3, null], family:"shell", usage:["jazz-comping", "bossa"], difficulty:2, popularity:66, jazz:94, tags:["9th", "shell"]},
  {quality:"m9", name:"m9 compact", frets:[null, 3, 5, 3, 3, null], family:"compact", usage:["bossa", "jazz-comping"], difficulty:3, popularity:54, jazz:93, tags:["compact", "9th"]},
  {quality:"m9", name:"Rootless m9 high", frets:[null, null, 3, 3, 4, 6], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:40, jazz:94, rootless:true, tags:["rootless", "top-set"]},
  {quality:"m9", name:"m9 chord melody", frets:[8, null, 8, 8, 10, null], family:"drop2", usage:["solo-guitar"], difficulty:4, popularity:34, jazz:91, tags:["9th", "solo"]},
  {quality:"9", name:"9 shell color", frets:[null, 3, 2, 3, 3, null], family:"shell", usage:["jazz-comping", "funk"], difficulty:2, popularity:82, jazz:94, tags:["9th", "shell"]},
  {quality:"9", name:"9 root grip", frets:[8, null, 8, 9, 8, 10], family:"drop2", usage:["jazz-comping", "blues"], difficulty:4, popularity:60, jazz:93, tags:["9th", "drop2"]},
  {quality:"9", name:"9 funk small", frets:[null, null, 8, 7, 8, 8], family:"compact", usage:["funk"], difficulty:2, popularity:74, jazz:86, tags:["funk", "compact"]},
  {quality:"9", name:"Rootless 9", frets:[null, null, 2, 3, 3, 3], family:"rootless", usage:["jazz-comping", "funk"], difficulty:3, popularity:66, jazz:96, rootless:true, tags:["rootless", "9th"]},
  {quality:"9", name:"9 top-set", frets:[null, null, 10, 9, 11, 10], family:"drop2", usage:["solo-guitar", "jazz-comping"], difficulty:4, popularity:36, jazz:91, tags:["top-set"]},
  {quality:"13", name:"Rootless 13", frets:[null, null, 2, 3, 3, 5], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:72, jazz:99, rootless:true, tags:["rootless", "13th"]},
  {quality:"13", name:"13 shell", frets:[null, 3, 2, 3, 5, null], family:"shell", usage:["jazz-comping", "funk"], difficulty:3, popularity:67, jazz:95, tags:["13th", "shell"]},
  {quality:"13", name:"13 compact", frets:[8, null, 8, 9, 10, null], family:"compact", usage:["jazz-comping", "funk"], difficulty:4, popularity:56, jazz:94, tags:["13th", "compact"]},
  {quality:"13", name:"13 bossa", frets:[null, 3, 2, 2, 3, 5], family:"compact", usage:["bossa"], difficulty:4, popularity:46, jazz:94, tags:["bossa", "13th"]},
  {quality:"13", name:"Rootless 13 high", frets:[null, null, 8, 9, 10, 10], family:"rootless", usage:["jazz-comping"], difficulty:5, popularity:34, jazz:96, rootless:true, tags:["rootless", "top-set"]},
  {quality:"6/9", name:"6/9 color", frets:[null, 3, 2, 2, 3, 3], family:"compact", usage:["bossa", "jazz-comping"], difficulty:3, popularity:70, jazz:95, tags:["bossa", "6th", "9th"]},
  {quality:"6/9", name:"Open 6/9-ish", frets:[null, 3, 2, 2, 3, 0], family:"open", usage:["pop", "bossa"], difficulty:2, popularity:58, jazz:82, tags:["open", "6th", "9th"]},
  {quality:"6/9", name:"6/9 drop2", frets:[8, null, 7, 7, 8, 8], family:"drop2", usage:["bossa", "solo-guitar"], difficulty:4, popularity:44, jazz:92, tags:["drop2", "6th", "9th"]},
  {quality:"6/9", name:"6/9 shell", frets:[null, 3, 2, 2, null, null], family:"shell", usage:["bossa", "jazz-comping"], difficulty:2, popularity:52, jazz:90, tags:["shell"]},
  {quality:"6/9", name:"Rootless 6/9", frets:[null, null, 2, 2, 3, 3], family:"rootless", usage:["bossa", "jazz-comping"], difficulty:3, popularity:49, jazz:93, rootless:true, tags:["rootless"]},
  {quality:"m11", name:"m11 rootless", frets:[null, null, 1, 3, 3, 1], family:"rootless", usage:["jazz-comping", "bossa"], difficulty:4, popularity:52, jazz:96, rootless:true, tags:["rootless", "11th"]},
  {quality:"m11", name:"m11 compact", frets:[null, 3, 1, 3, 3, 1], family:"compact", usage:["jazz-comping"], difficulty:4, popularity:48, jazz:94, tags:["11th", "compact"]},
  {quality:"m11", name:"m11 shell", frets:[null, 3, 1, 3, 1, null], family:"shell", usage:["jazz-comping"], difficulty:2, popularity:50, jazz:91, tags:["shell", "11th"]},
  {quality:"m11", name:"m11 top color", frets:[null, null, 8, 8, 8, 10], family:"drop2", usage:["solo-guitar"], difficulty:4, popularity:34, jazz:91, tags:["top-set", "11th"]},
  {quality:"7sus4", name:"7sus4 open-ish", frets:[null, 3, 3, 3, 1, 1], family:"compact", usage:["pop", "jazz-comping"], difficulty:3, popularity:54, jazz:82, tags:["sus"]},
  {quality:"7sus4", name:"7sus4 shell", frets:[null, 3, 3, 3, null, null], family:"shell", usage:["jazz-comping", "funk"], difficulty:2, popularity:58, jazz:88, tags:["sus", "shell"]},
  {quality:"7sus4", name:"9sus compact", frets:[null, 3, 3, 3, 3, null], family:"compact", usage:["funk", "jazz-comping"], difficulty:2, popularity:62, jazz:90, tags:["sus", "9th"]},
  {quality:"7sus4", name:"Rootless 13sus", frets:[null, null, 3, 3, 3, 5], family:"rootless", usage:["jazz-comping"], difficulty:4, popularity:41, jazz:92, rootless:true, tags:["rootless", "sus"]},
  {quality:"7alt", name:"Rootless 7alt b9#5", frets:[null, null, 2, 3, 3, 4], family:"rootless", usage:["jazz-comping"], difficulty:5, popularity:50, jazz:99, rootless:true, tags:["rootless", "altered", "b9"]},
  {quality:"7alt", name:"7alt #9 grip", frets:[8, null, 8, 9, 9, null], family:"compact", usage:["jazz-comping"], difficulty:4, popularity:56, jazz:96, tags:["altered", "#9"]},
  {quality:"7alt", name:"7b9 shell", frets:[null, 3, 2, 3, 2, null], family:"shell", usage:["jazz-comping"], difficulty:3, popularity:60, jazz:96, tags:["b9", "shell"]},
  {quality:"7alt", name:"7#9 compact", frets:[null, 3, 2, 3, 4, null], family:"compact", usage:["jazz-comping", "funk"], difficulty:3, popularity:58, jazz:95, tags:["#9", "compact"]},
  {quality:"7alt", name:"Rootless 7alt high", frets:[null, null, 8, 9, 9, 10], family:"rootless", usage:["jazz-comping"], difficulty:5, popularity:36, jazz:98, rootless:true, tags:["rootless", "altered"]},
  {quality:"maj7", name:"Guide tone mini", frets:[null, null, 2, 4, null, null], family:"shell", usage:["jazz-comping"], difficulty:1, popularity:55, jazz:87, tags:["guide-tones"]},
  {quality:"maj7", name:"Bossa soft voicing", frets:[null, 3, null, 4, 5, 3], family:"drop2", usage:["bossa"], difficulty:3, popularity:52, jazz:91, tags:["bossa"]},
  {quality:"maj7", name:"Solo high maj7", frets:[null, null, 10, 12, 12, 12], family:"drop2", usage:["solo-guitar"], difficulty:4, popularity:34, jazz:88, tags:["top-set"]},
  {quality:"m7", name:"Guide tone mini", frets:[null, null, 1, 3, null, null], family:"shell", usage:["jazz-comping"], difficulty:1, popularity:56, jazz:87, tags:["guide-tones"]},
  {quality:"m7", name:"Bossa soft voicing", frets:[null, 3, null, 3, 4, 3], family:"drop2", usage:["bossa"], difficulty:3, popularity:54, jazz:91, tags:["bossa"]},
  {quality:"m7", name:"Solo high m7", frets:[null, null, 10, 12, 11, 11], family:"drop2", usage:["solo-guitar"], difficulty:4, popularity:32, jazz:88, tags:["top-set"]},
  {quality:"7", name:"Guide tone mini", frets:[null, null, 2, 3, null, null], family:"shell", usage:["jazz-comping"], difficulty:1, popularity:58, jazz:88, tags:["guide-tones"]},
  {quality:"7", name:"Bossa dominant", frets:[null, 3, null, 3, 5, 3], family:"drop2", usage:["bossa"], difficulty:3, popularity:55, jazz:91, tags:["bossa"]},
  {quality:"7", name:"Solo high 7", frets:[null, null, 10, 12, 11, 12], family:"drop2", usage:["solo-guitar"], difficulty:4, popularity:33, jazz:88, tags:["top-set"]},
];

export const LIBRARY_META = {
  version: 'v2-phase1-seed',
  templateCount: 98,
  focus: 'maj7 / m7 / 7 / m7b5 / dim7 core forms plus starter tensions',
  nextTarget: '200+ forms with stronger drop2/drop3/rootless coverage' 
};